server:
  port: 9000
  servlet:
    session:
      cookie:
        same-site: lax

spring:
  application:
    name: auth-server

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web: DEBUG

hanko:
  passkey:
    api-url: http://localhost:8000
    tenant-id: ${HANKO_TENANT_ID:}
    api-key: ${HANKO_API_KEY:}
