server:
  port: 9001
  servlet:
    session:
      cookie:
        same-site: lax

spring:
  application:
    name: client-app
  security:
    oauth2:
      client:
        registration:
          client-app:
            provider: spring
            client-id: client-app
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:9001/login/oauth2/code/client-app"
            scope: openid, read
            client-name: client-app
        # 수정: provider 설정을 issuer-uri로 간소화
        provider:
          spring:
            issuer-uri: http://localhost:9000
